import { Doctor } from '@/lib/types';

export const mockDoctorsData: Doctor[] = [
  {
    id: '1',
    name: 'Aditya Sharma',
    image: 'https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician/ Internal Medicine Specialist',
    qualifications: 'MBBS, MD (Internal Medicine)',
    experience: 15,
    ratings: 92,
    reviews: 324,
    fees: 800,
    availableToday: true,
    availableTomorrow: true,
    gender: 'male',
    languages: ['English', 'Hindi'],
    specialties: ['Diabetes', 'Hypertension', 'Infectious Diseases'],
    location: 'Bangalore',
    hospital: 'Apollo Hospitals Health City Unit, Bangalore'
  },
  {
    id: '2',
    name: 'Priya Patel',
    image: 'https://images.pexels.com/photos/5214958/pexels-photo-5214958.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician/ Internal Medicine Specialist',
    qualifications: 'MBBS, DNB (Family Medicine)',
    experience: 8,
    ratings: 94,
    reviews: 187,
    fees: 700,
    availableToday: false,
    availableTomorrow: true,
    gender: 'female',
    languages: ['English', 'Hindi', 'Gujarati'],
    specialties: ['Women\'s Health', 'Preventive Care'],
    location: 'Delhi',
    hospital: 'Apollo Clinic Patel Nagar, Delhi'
  },
  {
    id: '3',
    name: 'Rajiv Mehta',
    image: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician/ Internal Medicine Specialist',
    qualifications: 'MBBS, MD (General Medicine)',
    experience: 20,
    ratings: 98,
    reviews: 412,
    fees: 1200,
    availableToday: true,
    availableTomorrow: true,
    gender: 'male',
    languages: ['English', 'Hindi', 'Marathi'],
    specialties: ['Critical Care', 'Respiratory Diseases', 'Cardiology'],
    location: 'Mumbai',
    hospital: 'Apollo Hospitals Navi Mumbai'
  },
  {
    id: '4',
    name: 'Ananya Singh',
    image: 'https://images.pexels.com/photos/5407206/pexels-photo-5407206.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician/ Internal Medicine Specialist',
    qualifications: 'MBBS, DCH',
    experience: 6,
    ratings: 90,
    reviews: 98,
    fees: 600,
    availableToday: true,
    availableTomorrow: false,
    gender: 'female',
    languages: ['English', 'Hindi', 'Bengali'],
    specialties: ['Pediatrics', 'Adolescent Health'],
    location: 'Kolkata',
    hospital: 'Apollo Gleneagles Hospital, Kolkata'
  },
  {
    id: '5',
    name: 'Vikram Desai',
    image: 'https://images.pexels.com/photos/4225880/pexels-photo-4225880.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician/ Internal Medicine Specialist',
    qualifications: 'MBBS, MD, DM (Endocrinology)',
    experience: 18,
    ratings: 97,
    reviews: 276,
    fees: 1500,
    availableToday: false,
    availableTomorrow: true,
    gender: 'male',
    languages: ['English', 'Hindi', 'Gujarati'],
    specialties: ['Diabetes', 'Thyroid Disorders', 'Hormonal Imbalances'],
    location: 'Ahmedabad',
    hospital: 'Apollo Hospitals International Limited, Ahmedabad'
  },
  {
    id: '6',
    name: 'Meera Reddy',
    image: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician',
    qualifications: 'MBBS, MD (Internal Medicine)',
    experience: 12,
    ratings: 4.6,
    reviews: 156,
    fees: 900,
    availableToday: true,
    availableTomorrow: true,
    gender: 'female',
    languages: ['English', 'Hindi', 'Telugu', 'Tamil'],
    specialties: ['Acute Illnesses', 'Chronic Disease Management']
  },
  {
    id: '7',
    name: 'Arjun Nair',
    image: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'Internal Medicine',
    qualifications: 'MBBS, MD (General Medicine)',
    experience: 10,
    ratings: 4.7,
    reviews: 132,
    fees: 850,
    availableToday: false,
    availableTomorrow: false,
    gender: 'male',
    languages: ['English', 'Hindi', 'Malayalam'],
    specialties: ['Infectious Diseases', 'Travel Medicine']
  },
  {
    id: '8',
    name: 'Neha Gupta',
    image: 'https://images.pexels.com/photos/5214949/pexels-photo-5214949.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician',
    qualifications: 'MBBS, DNB (Family Medicine)',
    experience: 7,
    ratings: 4.5,
    reviews: 89,
    fees: 700,
    availableToday: true,
    availableTomorrow: true,
    gender: 'female',
    languages: ['English', 'Hindi'],
    specialties: ['Preventive Care', 'Women\'s Health', 'Geriatric Care']
  },
  {
    id: '9',
    name: 'Suresh Kumar',
    image: 'https://images.pexels.com/photos/5327656/pexels-photo-5327656.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'Internal Medicine',
    qualifications: 'MBBS, MD, DM (Gastroenterology)',
    experience: 22,
    ratings: 4.9,
    reviews: 405,
    fees: 1800,
    availableToday: true,
    availableTomorrow: false,
    gender: 'male',
    languages: ['English', 'Hindi', 'Tamil'],
    specialties: ['Digestive Disorders', 'Liver Diseases']
  },
  {
    id: '10',
    name: 'Kavita Joshi',
    image: 'https://images.pexels.com/photos/5215017/pexels-photo-5215017.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician',
    qualifications: 'MBBS, MD (Internal Medicine)',
    experience: 9,
    ratings: 4.6,
    reviews: 118,
    fees: 750,
    availableToday: false,
    availableTomorrow: true,
    gender: 'female',
    languages: ['English', 'Hindi', 'Marathi'],
    specialties: ['Fever Management', 'Common Ailments']
  },
  {
    id: '11',
    name: 'Rahul Kapoor',
    image: 'https://images.pexels.com/photos/5452291/pexels-photo-5452291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'Internal Medicine',
    qualifications: 'MBBS, MD, DM (Cardiology)',
    experience: 16,
    ratings: 4.8,
    reviews: 267,
    fees: 1400,
    availableToday: true,
    availableTomorrow: true,
    gender: 'male',
    languages: ['English', 'Hindi', 'Punjabi'],
    specialties: ['Heart Diseases', 'Hypertension']
  },
  {
    id: '12',
    name: 'Anjali Verma',
    image: 'https://images.pexels.com/photos/5407038/pexels-photo-5407038.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician',
    qualifications: 'MBBS, MD (General Medicine)',
    experience: 11,
    ratings: 4.7,
    reviews: 143,
    fees: 850,
    availableToday: false,
    availableTomorrow: true,
    gender: 'female',
    languages: ['English', 'Hindi'],
    specialties: ['Geriatric Care', 'Chronic Disease Management']
  },
  {
    id: '13',
    name: 'Sanjay Iyer',
    image: 'https://images.pexels.com/photos/5215021/pexels-photo-5215021.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'Internal Medicine',
    qualifications: 'MBBS, MD, DM (Pulmonology)',
    experience: 14,
    ratings: 4.8,
    reviews: 189,
    fees: 1200,
    availableToday: true,
    availableTomorrow: false,
    gender: 'male',
    languages: ['English', 'Hindi', 'Tamil', 'Kannada'],
    specialties: ['Respiratory Diseases', 'Sleep Disorders', 'Asthma']
  },
  {
    id: '14',
    name: 'Deepa Menon',
    image: 'https://images.pexels.com/photos/5215131/pexels-photo-5215131.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'General Physician',
    qualifications: 'MBBS, DNB (Family Medicine)',
    experience: 8,
    ratings: 4.5,
    reviews: 97,
    fees: 700,
    availableToday: true,
    availableTomorrow: true,
    gender: 'female',
    languages: ['English', 'Hindi', 'Malayalam'],
    specialties: ['Women\'s Health', 'Preventive Care']
  },
  {
    id: '15',
    name: 'Karthik Rao',
    image: 'https://images.pexels.com/photos/5452268/pexels-photo-5452268.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    specialization: 'Internal Medicine',
    qualifications: 'MBBS, MD (General Medicine)',
    experience: 13,
    ratings: 4.7,
    reviews: 156,
    fees: 950,
    availableToday: false,
    availableTomorrow: true,
    gender: 'male',
    languages: ['English', 'Hindi', 'Kannada', 'Telugu'],
    specialties: ['Metabolic Disorders', 'Preventive Medicine']
  }
];